version: '3'
services:
  app1:
    build: .
    environment:
      APP_NAME: "App1"
      PORT: 3000
    ports:
      - "3001:3000"

  app2:
    build: .
    environment:
      APP_NAME: "App2"
      PORT: 3000
    ports:
      - "3002:3000"

  app3:
    build: .
    environment:
      APP_NAME: "App3"
      PORT: 3000
    ports:
      - "3003:3000"
